"""add minimum engagement to campagn

Revision ID: 16eae054d37e
Revises: 
Create Date: 2025-08-14 23:37:47.701466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16eae054d37e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_engagement', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_model', schema=None) as batch_op:
        batch_op.drop_column('minimum_engagement')

    # ### end Alembic commands ###
